export interface Emoji {
  src: string
  title: string
  group: string
}

const emojis: Emoji[] = [
  { src: '0.gif', title: '[微笑]', group: '1' },
  { src: '1.gif', title: '[撇嘴]', group: '1' },
  { src: '2.gif', title: '[色]', group: '1' },
  { src: '3.gif', title: '[发呆]', group: '1' },
  { src: '4.gif', title: '[得意]', group: '1' },
  { src: '5.gif', title: '[流泪]', group: '1' },
  { src: '6.gif', title: '[害羞]', group: '1' },
  { src: '7.gif', title: '[闭嘴]', group: '1' },
  { src: '8.gif', title: '[钱]', group: '1' },
  { src: '9.gif', title: '[大哭]', group: '1' },
  { src: '10.gif', title: '[尴尬]', group: '1' },
  { src: '11.gif', title: '[发怒]', group: '1' },
  { src: '12.gif', title: '[调皮]', group: '1' },
  { src: '13.gif', title: '[龇牙]', group: '1' },
  { src: '14.gif', title: '[惊讶]', group: '1' },
  { src: '15.gif', title: '[难过]', group: '1' },
  { src: '16.gif', title: '[酷]', group: '1' },
  { src: '17.gif', title: '[冷汗]', group: '1' },
  { src: '18.gif', title: '[抓狂]', group: '1' },
  { src: '19.gif', title: '[吐]', group: '1' },

  { src: '20.gif', title: '[偷笑]', group: '2' },
  { src: '21.gif', title: '[可爱]', group: '2' },
  { src: '22.gif', title: '[白眼]', group: '2' },
  { src: '23.gif', title: '[傲慢]', group: '2' },
  { src: '24.gif', title: '[饥饿]', group: '2' },
  { src: '25.gif', title: '[困]', group: '2' },
  { src: '26.gif', title: '[惊恐]', group: '2' },
  { src: '27.gif', title: '[流汗]', group: '2' },
  { src: '28.gif', title: '[憨笑]', group: '2' },
  { src: '29.gif', title: '[大兵]', group: '2' },
  { src: '30.gif', title: '[奋斗]', group: '2' },
  { src: '31.gif', title: '[咒骂]', group: '2' },
  { src: '32.gif', title: '[疑问]', group: '2' },
  { src: '33.gif', title: '[嘘]', group: '2' },
  { src: '34.gif', title: '[晕]', group: '2' },
  { src: '35.gif', title: '[折磨]', group: '2' },
  { src: '36.gif', title: '[衰]', group: '2' },
  { src: '37.gif', title: '[骷髅]', group: '2' },
  { src: '38.gif', title: '[敲打]', group: '2' },
  { src: '39.gif', title: '[再见]', group: '2' },

  { src: '40.gif', title: '[擦汗]', group: '3' },
  { src: '41.gif', title: '[抠鼻]', group: '3' },
  { src: '42.gif', title: '[鼓掌]', group: '3' },
  { src: '43.gif', title: '[糗大]', group: '3' },
  { src: '44.gif', title: '[坏笑]', group: '3' },
  { src: '45.gif', title: '[左哼]', group: '3' },
  { src: '46.gif', title: '[右哼]', group: '3' },
  { src: '47.gif', title: '[哈欠]', group: '3' },
  { src: '48.gif', title: '[鄙视]', group: '3' },
  { src: '49.gif', title: '[委屈]', group: '3' },
  { src: '50.gif', title: '[快哭]', group: '3' },
  { src: '51.gif', title: '[阴险]', group: '3' },
  { src: '52.gif', title: '[亲亲]', group: '3' },
  { src: '53.gif', title: '[惊吓]', group: '3' },
  { src: '54.gif', title: '[可怜]', group: '3' },
  { src: '55.gif', title: '[菜刀]', group: '3' },
  { src: '56.gif', title: '[西瓜]', group: '3' },
  { src: '57.gif', title: '[啤酒]', group: '3' },
  { src: '58.gif', title: '[篮球]', group: '3' },
  { src: '59.gif', title: '[乒乓]', group: '3' },

  { src: '60.gif', title: '[拥抱]', group: '4' },
  { src: '61.gif', title: '[握手]', group: '4' },
  { src: '62.gif', title: '[红包]', group: '4' },
  { src: '63.gif', title: '[互粉]', group: '4' },
  { src: '64.gif', title: '[Good]', group: '4' },
  { src: '65.gif', title: '[来]', group: '4' },
  { src: '66.gif', title: '[NO]', group: '4' },
  { src: '67.gif', title: '[弱]', group: '4' },
  { src: '68.gif', title: '[心碎]', group: '4' },
  { src: '69.gif', title: '[神马]', group: '4' },
  { src: '70.gif', title: '[心动]', group: '4' },
  { src: '71.gif', title: '[耶]', group: '4' },
  { src: '72.gif', title: '[威武]', group: '4' },
  { src: '73.gif', title: '[生病]', group: '4' },
  { src: '74.gif', title: '[呕吐]', group: '4' },
  { src: '75.gif', title: '[囧]', group: '4' },
  { src: '76.gif', title: '[生日]', group: '4' },
  { src: '77.gif', title: '[蜡烛]', group: '4' },
  { src: '78.gif', title: '[围观]', group: '4' },
  { src: '79.gif', title: '[猪]', group: '4' }
]

export default emojis
